# These version constraints come from Zendar's internal libraries that
# require this package, just to reduce the chance of version
# inconsistencies.

[[tool.pdm.source]]
url = "https://download.pytorch.org/whl/cu126"
verify_ssl = true
name = "torch-cu126"
type = "find-links"


[project]
name = "torchsparse"
description = ""
authors = []
dependencies = [
    "torch==2.6.0+cu126",
    "tqdm",
    "numpy",
    "setuptools",
    "twine==6.1.0",
    "keyring>=25.6.0",
    "keyrings-google-artifactregistry-auth>=1.1.2",
]
requires-python = ">=3.11,<3.12"
readme = "README.md"
license = {text = "MIT"}
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "torchsparse.__version__"}

[build-system]
requires = ["torch==2.6.0+cu126", "tqdm", "numpy", "setuptools", "twine==6.1.0"]
