# Keep these version constraints consistent with Zendar's
# internal libraries that require this package to reduce
# the chance of version inconsistencies.

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128" }
]

[project]
name = "torchsparse"
description = ""
authors = []
dependencies = [
    "torch==2.10.0+cu128",
    "tqdm",
    "numpy",
    "setuptools",
]
requires-python = ">=3.11,<3.12"
readme = "README.md"
license = {text = "MIT"}
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "torchsparse.__version__"}

[tool.setuptools]
include-package-data = true

[build-system]
requires = [
    "torch==2.10.0+cu128",
    "tqdm",
    "numpy",
    "setuptools",
]

[dependency-groups]
dev = [
    "twine>=6.1.0",
]
