[build-system]
# These version constraints come from Zendar's internal libraries that
# require this package, just to reduce the chance of version
# inconsistencies.
requires = ["torch==1.11.0+cu113", "tqdm", "numpy", "setuptools"]
