name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends clang-format
    - uses: actions/checkout@v4
    - run: |
        git fetch origin ${{ github.base_ref }}
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: >
          --from-ref origin/${{ github.base_ref }}
          --to-ref HEAD
